spring.application.name=hostel-backend
server.port=8080

spring.datasource.url=jdbc:mysql://localhost:3307/hostel_db?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=test123
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

# Email Settings
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=jayawarnatharuka@gmail.com
spring.mail.password=lbuz stxf vyes dqqr
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
admin.email=jayawarnatharuka@gmail.com

# PayHere Configuration
payhere.merchant.id=1233062
payhere.merchant.secret=MzM4OTA3NTQyMTkxNzQyNzIxOTEzNjAyNDA3ODE4MTM1NDAxODQ=
payhere.currency=LKR
payhere.notify.url=https://ursula-brainy-jessi.ngrok-free.dev/payments/notify

spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=myuser
spring.rabbitmq.password=mypassword


# Cloudinary Config
cloudinary.cloud_name=djojyt6nc
cloudinary.api_key=889336416771497
cloudinary.api_secret=2FreRvTvfVOkL3Cm5btWBla9QAQ